### ISSUE TITLE
[Bug]: Unsupported config key GW_OPENAI_API_KEY: Must be 51 characters long

### ISSUE THREAD

**Issue by abnerjacobsen** [aiFdn/gitwz#10]
### GitWiz Version

6.6.0

### Node Version

18.19.1

### NPM Version

9.2.0

### What OS are you seeing the problem on?

Other Linux Distro

### What happened?

When I try to set my OPENAI key got this error:

ERROR  Unsupported config key GW_OPENAI_API_KEY: Must be 51 characters long

### Expected Behavior

Must accept API keys with the new naming convention from OPENAI

### Current Behavior

The setting of the API key is reject by gitwz.

### Steps to Reproduce

gw config set GW_OPENAI_API_KEY=sk-proj-swSkOU...

### Relevant log output

```shell
┌  gitwz — config
│
└   ERROR  Unsupported config key GW_OPENAI_API_KEY: Must be 51 characters long
```

**Comment by SHSharkar** [comment]
Thank you, @abnerjacobsen, for submitting the bug report.

I will take a look at the issue and resolve it as soon as possible. Expect a new fix to be deployed shortly.

**Comment by SHSharkar** [comment]
@abnerjacobsen 

I have fixed the OpenAI API key length issues in the package. 

Please install the latest version of the package by running:

```
npm install -g gitwz@latest
```

The fixes are applied to the following release tag: v7.1.0

https://github.com/aiFdn/gitwz/releases/tag/v7.1.0

![image](https://github.com/aiFdn/gitwz/assets/12555542/2cdc7e07-4998-4196-92c1-794063304788)

**Comment by SHSharkar** [comment]
Since the problem has been resolved, I'm going to close the issue. 

Feel free to leave a comment if you find any further issues.
